# Import Numpy

In [559]:
import numpy as np

# Writing matrices

In [560]:
A = np.array([[1,2],[3,4]])
B = np.array([[1,2],[3,4],[5,6]])
C = np.array([[1,2,3],[4,5,6]])

## For matrix shape and size

In [561]:
print(B.shape, B.size)

(3, 2) 6


## To stack matrices

In [562]:
D = np.hstack([A,C])
print(D)

[[1 2 1 2 3]
 [3 4 4 5 6]]


## Powers and basic operations

In [563]:
# Power
A**2
np.linalg.matrix_power(A,2)

# Multuplications
A@C

# Division
A/4

array([[0.25, 0.5 ],
       [0.75, 1.  ]])

# Inverse and Determinant

### Inversible matrix

In [564]:
# Invertible matrix
M = np.array([[0,1,1],[-2,-1,-2],[1,1,2]])
M_inv = np.linalg.inv(M)
Det_M = np.linalg.det(M)
print("Inverse:\n", M_inv)
print("\nProof that it is invertible using M_inv@M:\n", M_inv@M)
print("\nProof that it is invertible using the det:\n", Det_M)

Inverse:
 [[-0. -1. -1.]
 [ 2. -1. -2.]
 [-1.  1.  2.]]

Proof that it is invertible using M_inv@M:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Proof that it is invertible using the det:
 1.0


### Not invertible matrix

In [565]:
H = np.array([[1,2,3],[4,5,6],[7,8,9]])
H_inv = np.linalg.inv(H)
Det_H = np.linalg.det(H)
print("Not invertible:\n", H_inv)
print("\nProof that it is not invertible using H_inv@H:\n", H_inv@H)
print("\nProof that it is not invertible using the det:\n", Det_H)

Not invertible:
 [[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]

Proof that it is not invertible using H_inv@H:
 [[ 12.   16.   12. ]
 [-10.  -16.   -6. ]
 [  1.5   4.    2.5]]

Proof that it is not invertible using the det:
 -9.51619735392994e-16


## Identity matrix and diagonals

### Identity with multiple dimensions

In [566]:
I = np.eye(5)
print(I)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


### Diagonal

In [567]:
E = np.diag([5,5,3,4])
print(E)

[[5 0 0 0]
 [0 5 0 0]
 [0 0 3 0]
 [0 0 0 4]]


### Zero matrix

In [568]:
Zero = np.zeros([3,4])
print(Zero)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


### Block command

In [569]:
F = np.block([[A,C], [np.eye(2), np.zeros([2,3])]])
print(F)

[[1. 2. 1. 2. 3.]
 [3. 4. 4. 5. 6.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]]


# Eigenvalues and Eigenvectors

In [570]:
A = np.array([[1,2],[-1,4]])
ev, S = np.linalg.eig(A)
print("Eigenvalues:\n",ev)
print("\nInvertible Matrix S 'inv(S)@A@S = M':\n",S)
print("\n!! Values of S are the Eigenbasis of M !!")

Eigenvalues:
 [2. 3.]

Invertible Matrix S 'inv(S)@A@S = M':
 [[-0.89442719 -0.70710678]
 [-0.4472136  -0.70710678]]

!! Values of S are the Eigenbasis of M !!


### ev, S

In [571]:
SINGLE = np.linalg.eig(A)
print(SINGLE)

print("\nEigenvalues:\n",SINGLE[0])
print("\nEigenvectors:\n",SINGLE[1])

EigResult(eigenvalues=array([2., 3.]), eigenvectors=array([[-0.89442719, -0.70710678],
       [-0.4472136 , -0.70710678]]))

Eigenvalues:
 [2. 3.]

Eigenvectors:
 [[-0.89442719 -0.70710678]
 [-0.4472136  -0.70710678]]


### Proof of eig(S)

In [572]:
M_S = np.linalg.inv(S)@A@S
print(M_S)

[[2. 0.]
 [0. 3.]]


In [573]:
Z = np.array([[2,1],[1,1]])
Z_S = np.linalg.inv(Z)@A@Z
print(Z_S)

[[2. 0.]
 [0. 3.]]


# Norm

In [574]:
a,b = np.array([[1],[-5],[6]]), np.array([[0],[-2],[7]])

### Manhattan norm $||a_1||$

In [575]:
print(np.linalg.norm(a,1))

12.0


### Eucledian norm $||a_2||$

In [576]:
print(np.linalg.norm(a))
print(np.linalg.norm(a,2))

7.874007874011811
7.874007874011811


### Maximum norm $||a_\text{max}||$

In [577]:
print(np.linalg.norm(a,np.inf))

6.0


# Scalar product

In [578]:
print(sum(a*b))
print(a.T@b)

[52]
[[52]]


### Pivot positions

In [579]:
s = (a.T@b)[0,0]
print(s)

print(a[0,0])

52
1


# Gram - Schmidt

In [580]:
u = np.array([[1],[2],[0]])
v = np.array([[8],[1],[-6]])
w = np.array([[0],[0],[1]])

A = np.hstack([u,v,w])
print(A)

[[ 1  8  0]
 [ 2  1  0]
 [ 0 -6  1]]


## Orthonormal (q) and upper-triangular (r)


In [581]:
Q,R = np.linalg.qr(A)
print(Q,"\n\n",R)

[[-0.4472136   0.66666667  0.59628479]
 [-0.89442719 -0.33333333 -0.2981424 ]
 [-0.         -0.66666667  0.74535599]] 

 [[-2.23606798 -4.47213595  0.        ]
 [ 0.          9.         -0.66666667]
 [ 0.          0.          0.74535599]]


### Proof of the Transformation matrix (r)

In [582]:
# Q@R gives the original matrix A
print(Q@R)

[[ 1.00000000e+00  8.00000000e+00 -7.07465566e-17]
 [ 2.00000000e+00  1.00000000e+00  8.13329108e-18]
 [ 0.00000000e+00 -6.00000000e+00  1.00000000e+00]]


### Norm of Q

In [583]:
P = Q[0,0]**2 + Q[1,0]**2 + Q[2,0]**2
print(P)

0.9999999999999997


# Linear systems

In [584]:
from scipy import linalg

## Linear system with its inverse

$$\begin{align*}
A\cdot \mathbf{x} &= \mathbf{b}\\
A^{-1}\cdot A \cdot \mathbf{x} &= A^{-1}\cdot \mathbf{b}\\
\mathbf{x} &= A^{-1}\cdot \mathbf{b}
\end{align*}$$

In [585]:
A = np.array([[2,-3],[3,-5]])
d = np.linalg.det(A)
print(d)

-0.9999999999999996


In [586]:
b = np.array([[5],[6]])
x = np.linalg.inv(A)@b
print(x)

[[7.]
 [3.]]


### Proof of invertible matrix x

In [587]:
print(A@x)

[[5.]
 [6.]]


## Using scipy

In [588]:
B = np.array([[-2,3,1],[3,-2,0],[1,0,3]])
d = linalg.det(B)
c = np.array([[7],[-3],[2]])
print(d)

-13.0


In [589]:
xs = linalg.inv(B)@c
print(xs)

print("\n",c-B@xs)

[[0.84615385]
 [2.76923077]
 [0.38461538]]

 [[8.8817842e-16]
 [8.8817842e-16]
 [8.8817842e-16]]


In [590]:
xsol = linalg.solve(B,c)
print(c-B@xsol)

[[0.]
 [0.]
 [0.]]


# Square system with singular coefficient matrix

Singular = not invertible matrix, ie det = 0; 0 solutions; $\infty$ solutions 

In [591]:
A = np.array([[2,-6],[-1,3]])
d = np.linalg.det(A)
b = np.array([[-2],[1]])
print(d)

0.0


## Rank of a matrix

If $A =$ square and $\det A = 0$,

rk $A =$ rk $A\big|b \to \infty-$ many solutions 
rk $A \neq$ rk $A\big|b \to 0$ solutions 


In [592]:
rkA = np.linalg.matrix_rank(A)
print(rkA)

rkAb = np.linalg.matrix_rank(np.hstack([A,b]))
print(rkAb)

1
1


In [593]:
x_a = linalg.lstsq(A,b)[0]
print(x_a)

xNew = linalg.lstsq(A,b)[0]
print("\n",A@xNew)

[[-0.1]
 [ 0.3]]

 [[-2.]
 [ 1.]]


## Rank check
### To find $\infty$-many solutions:
$$\text{Sol} = x_p + \lambda_1n_1 + \lambda_2n_2 + \dots + \lambda_rn_r$$
$$\ker A = \left\{n_1, n_2, \dots, n_r \right\}$$
$$A\cdot n_1 = 0 \Longrightarrow A\left(x_p+n_1\right) = Ax_p + An_1 = \boxed{Ax_p = \mathbf{b}}$$

In [594]:
n = linalg.null_space(A)
print("Kernel:\n",n)

# Proof
print("\nKernel check:\n",A@n)

# Using 7 (that ofc belongs to the kernel)
print("\nVector b using 7*n:\n", A@(xNew+7*n))

Kernel:
 [[-0.9486833 ]
 [-0.31622777]]

Kernel check:
 [[0.]
 [0.]]

Vector b using 7*n:
 [[-2.]
 [ 1.]]


### When we have 0 solutions:

$$\mathrm{rk}\ (A) \neq \mathrm{rk}\ (A\big|b)$$

In [595]:
b = np.array([[1],[1]])

print(rkA)
rkAb = np.linalg.matrix_rank(np.hstack([A,b]))
print(rkAb)

1
2


Proof that b $\neq$ A@x_b

In [596]:
x_b = linalg.lstsq(A,b)[0]
print(x_b)

print("\n",A@x_b)

[[ 0.02]
 [-0.06]]

 [[ 0.4]
 [-0.2]]


## Non-square matrix

In [611]:
A = np.array([[1,1,1],[1,1,1]])
b = np.array([[0],[1]])

rkA = np.linalg.matrix_rank(A)
print(rkA)

rkAb = np.linalg.matrix_rank(np.hstack([A,b]))
print(rkAb)

x_q = linalg.lstsq(A,b)[0]
print("\n",x_q,"\n\n",A@x_q)

print("\n",linalg.null_space(A))


1
2

 [[0.16666667]
 [0.16666667]
 [0.16666667]] 

 [[0.5]
 [0.5]]

 [[-8.16496581e-01 -6.99362418e-17]
 [ 4.08248290e-01 -7.07106781e-01]
 [ 4.08248290e-01  7.07106781e-01]]
