# SW08 InClass - Repetition and Programming  

This file is intended for interactive revision in the first hour of class. You write directly in the lines of code.

# Task 1 - Ball Surface  

- Define the function ``ball_surface(radius)``, which can calculate and **return** the surface area of ​​a sphere.
- Provide the function with **Type-Hints**
- Provide the function with a **Doc string**
- Give the function a **default value** of 5
- Test this

# Task 2 - Distance 2d  
- Define the function that can calculate the distance between two points in 2D: ``distance_2D((x1,y1)(x2,y2))``
- test these

In [3]:
import math

x1,y1 = float(input("Type x1: ")),float(input("Type y1: "))
x2,y2 = float(input("Type x2: ")),float(input("Type y2: "))

distance_x = (x2-x1)
distance_y = (y2-y1)

def distance_2D(distance_x,distance_y):
    distance = math.sqrt((distance_x)**2 + (distance_y)**2)
    print(f"The distance between points is {round(distance, 2)} units")

distance_2D(distance_x,distance_y)

The distance between points is 0.0 units


## Task 3 - Farenheit  

- Write a function ``celcius_fahrenheit(deg:float)`` which converts a temperature from **°Celcius to °Fahrenheit**.
- Extend the **input and return values** with **type hints**
- Create a **DocString** for the function

- Test the function
- 0°C = 32°F
- 37°C $\approx $ 98.6°F

In [4]:
deg = input("Degree in Celsius: ")
def celsius_farenheit(deg:float)->float:
    """
    Parameters
        deg: Degrees [°C]

    Result
        return far: Converted degrees [°F]
    """
    far = (float(deg)*9/5)+32
    return far

print(f"{float(deg)}°C are {celsius_farenheit(deg)}°F")

37.0°C are 98.6°F


# Array tasks  

## Array Arithmetic I  

Write a NumPy program to create an **8x8 matrix** and fill it with a **checkerboard pattern** (``1 = "white" and 0 = black``). Use **array indexing** to create the checkerboard.

<div style="text-align: center;">
<img src="https://houseofchess.co.za/cdn/shop/products/vinyllargeblack10.jpg?v=1639083970" alt="vinyl image" width="300px">
</div>



In [98]:
import numpy as np

checkboard_1 = np.array([[1,0,1,0,1,0,1,0],[0,1,0,1,0,1,0,1]]*4)
print(checkboard_1)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [100]:
checkboard_2 = np.ones((8,8)).astype(int)
checkboard_2[::2,1::2] = 0
checkboard_2[1::2,::2] = 0

print(checkboard_2)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


## Array Arithmetic II (OPTIONAL -> difficult)  

Write the function ``same_elements(arr_1,arr_2), `` which returns the **common values** between the **two 1D arrays**.

- Extend the function with **Type Hints** for the **input and return values** (Type array: ``np.nd_array``)
- Create a **DocString**
- Test the function with the following arrays:

```python
x = np.array([1,2,3,4,5,6,7,8])
y = np.array([4,5,6])
```

In [106]:
x = np.array([1,2,3,4,5,6,7,8])
y = np.array([4,5,6])

def same_elements(x:np.ndarray,y:np.ndarray)->np.ndarray:
    res =  []
    for elem in x:
        if elem in y:
            res.append(elem)
    return np.array(res)

print(same_elements(x,y))

[4 5 6]
