# Assignment work SW08 - PYTHON BASICS - Version 1.1

These are the self-study tasks for the semester week, which you will solve within a week in your JupyterHub environment. After completing your work, download a copy of the Jupyter notebook file locally to your laptop (right-click on the file in the JupyterHub file browser -> Download).

On ILIAS you will find the corresponding scheduled work assignments every week, where you will upload your solved Jupyter notebook file. After you have submitted your work, you will receive a corresponding sample solution for the work assignment. Your submission will not be corrected. Although the work assignments are marked "mandatory", there are no tests in the module. The grades from the tests during the semester count.

We wish you much success!

***
# Math Tasks


## Task 1 - deg2rad

- Define the **function** ``deg2rad(angle)`` which can convert the angle from **degrees** to **radians**. Use only standard operators (``+,-,...``)

- Test this

In [147]:
import numpy as np

deg = 180

def deg2rad(deg):
    rad = (deg*np.pi)/180
    return rad

print(f"{deg}° = {deg2rad(deg)} rad")

180° = 3.141592653589793 rad


# Task 2 - rad2deg

- Define the inverse function `rad2deg(radians)`. Use only standard operators (``+,-,...``)
- Test this

In [3]:
rad = np.pi/4

def rad2deg(rad):
    deg = (rad*180)/np.pi
    return deg

print(f"{rad} rad = {rad2deg(rad)}°")

0.7853981633974483 rad = 45.0°


# Task 3 - Ball Surface

- Define the function ``ball_surface(radius)``, which can calculate and **return** the **surface area of ​​a sphere**.
- Give the function a **default value** of `` 5``
- Test this

In [4]:
radius = input("Radius (cm): ")

def ball_surface(radius):
    surface_area = 4*np.pi*(float(radius)**2)
    return surface_area

print(f"The surface area of a sphere with r = {radius} cm is S_a = {ball_surface(radius):.1f} cm²")

Radius (cm):  5


The surface area of a sphere with r = 5 cm is S_a = 314.2 cm²


***
# Array tasks

## Array Creation I

Write a NumPy program to create a **3x3 matrix with values ​​between 2 and 10**. Assign the array to the variable ``arr_3d``.

**Tip:**
- ``np.arrange()``
- ``np.reshape()``

**Result:**

```
array([[ 2, 3, 4],
[ 5, 6, 7],
[ 8, 9, 10]])
```

In [5]:
def arr(n,m)->np.ndarray:
    array = np.arange(2,11).reshape((n,m))
    return array

arr_3d = arr(3,3)
print(arr_3d)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


# Invert

- Convert `arr_3d` to a **1D array**.
- Assign the result to the variable `arr_1d`.

**Result:**
```
array([ 2, 3, 4, 5, 6, 7, 8, 9, 10])
```

- **Invert** the order of the array (the first element becomes the last).


**Result**:
```
array([10, 9, 8, 7, 6, 5, 4, 3, 2])
```

In [6]:
arr_1d = arr_3d.reshape((9))

print(arr_1d[::-1])

[10  9  8  7  6  5  4  3  2]


## Read information
Print the following information from the arrays `arr_3d` and `arr_1d`.

- Shape
- Number of elements
- Number of dimensions

In [7]:
print(f"arr_3d has shape {arr_3d.shape}, {len(arr_3d)} elements, and {arr_3d.ndim} dimensions.")
print(f"arr_1d has shape {arr_1d.shape}, {len(arr_1d)} elements, and {arr_1d.ndim} dimensions.")

arr_3d has shape (3, 3), 3 elements, and 2 dimensions.
arr_1d has shape (9,), 9 elements, and 1 dimensions.


## Read values:

Read the following values ​​from `arr_1d` **in one statement** (via slicing):

- `[2,4,6]`
- `[10,9,8,7]`

Read the following values ​​from `arr_3d` **in a statement** (via slicing):

- `[2,3,4]`
- `[2,5,8]`
- `[[6,7],[9,10]]`


In [8]:
print(arr_1d[0:5:2])
print(arr_1d[:4:-1])

print(arr_3d[0])
print(arr_3d[:3,0])
print(", ".join(map(str, arr_3d[1:3,1:3])))

[2 4 6]
[10  9  8  7]
[2 3 4]
[2 5 8]
[6 7], [ 9 10]


## Array Arithmetic I

Create the following array & output it

![Alt ​​text](imgs/array_zeros.png)

In [9]:
def arr_5d(n):
    arr = np.ones((n,n))
    arr[1:-1,1:-1] -= 1
    return arr

print(arr_5d(5))

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


## Array manipulation
Given the following numpy array:
```python
import numpy as np
# --------------------
#  given np array
x = np.arange(50).reshape((10,5))
# --------------------
```

1. **Transpose** the given array and store it in a new variable.
- Print the **shape** of both arrays.

2. Perform a **matrix multiplication** of the given and the transposed array.
- Store the result as a new variable (`z`).
- Print the **form** of `z`
- Return the **number of dimensions** of `z`

3. **Reform`z`** into the form ``(10,10,1)``.
- Print the form of `z`
- Print the number of dimensions of `z`

4. **Type conversion:**
- Print the type of array `z`
- convert the array type to a `float`
- convert the type of the array to a `bool`
- what happens?

In [10]:
x = np.arange(50).reshape((10,5))
#1
t = x.transpose()
#2
z = x@t
print(z, z.shape)
#3
print(z.reshape(10,10,1), z.shape)
#4
print(type(z))
print(z.astype(float))
print(z.astype(bool)) # since the values are different from 0, every value return True

[[   30    80   130   180   230   280   330   380   430   480]
 [   80   255   430   605   780   955  1130  1305  1480  1655]
 [  130   430   730  1030  1330  1630  1930  2230  2530  2830]
 [  180   605  1030  1455  1880  2305  2730  3155  3580  4005]
 [  230   780  1330  1880  2430  2980  3530  4080  4630  5180]
 [  280   955  1630  2305  2980  3655  4330  5005  5680  6355]
 [  330  1130  1930  2730  3530  4330  5130  5930  6730  7530]
 [  380  1305  2230  3155  4080  5005  5930  6855  7780  8705]
 [  430  1480  2530  3580  4630  5680  6730  7780  8830  9880]
 [  480  1655  2830  4005  5180  6355  7530  8705  9880 11055]] (10, 10)
[[[   30]
  [   80]
  [  130]
  [  180]
  [  230]
  [  280]
  [  330]
  [  380]
  [  430]
  [  480]]

 [[   80]
  [  255]
  [  430]
  [  605]
  [  780]
  [  955]
  [ 1130]
  [ 1305]
  [ 1480]
  [ 1655]]

 [[  130]
  [  430]
  [  730]
  [ 1030]
  [ 1330]
  [ 1630]
  [ 1930]
  [ 2230]
  [ 2530]
  [ 2830]]

 [[  180]
  [  605]
  [ 1030]
  [ 1455]
  [ 1880]
  [ 

***
# Text comprehension + Python

In a bakery, **three** different types of **dough** $T_1, T_2, T_3$ are made from **four** different
**Types of flour** $M_1, M_2, M_3, M_4$ are produced. From the dough types **three** different
Types of **bread** $B_1, B_2, B_3$ baked.

The following **tables** show:

1. How many units of **each type of flour** are needed **per unit of dough** of the different **dough types**
2. How many units of **each type of dough** are needed per **loaf of bread**:

![text_1](imgs/text_1_eng.png)


Let $A$ be the $(4 × 3)$ matrix from the **first table (left)** and $B$ be the $(3 × 3)$ matrix
from the **second table**.

## Task

- Create the two Maritzen $A$ and $B$

- Calculate $C$ which is the matrix describing the number of units of **flour**
that is needed for a loaf of **bread** of type $B$ : Express the matrix $C$
by $A$ and $B$. **Give reasons for your answer**

- What shape does $C$ have?

- What does an arbitrary entry in $C_{ij}$ describe


In [161]:
arr_A = np.array([[3,1,1],[1,3,1],[2,1,1],[2,0,4]])
arr_B = np.array([[2,1,2],[2,1,0],[0,1,1]])
arr_C = arr_A@arr_B

print(f"Matrix A:\n{arr_A}\n\nMatrix B:\n{arr_B}\n\nAB:\n{arr_C}\n\nAB has a shape {arr_C.shape}\n\nC describes the number of units of flour that is needed for a loaf of bread")

Matrix A:
[[3 1 1]
 [1 3 1]
 [2 1 1]
 [2 0 4]]

Matrix B:
[[2 1 2]
 [2 1 0]
 [0 1 1]]

AB:
[[8 5 7]
 [8 5 3]
 [6 4 5]
 [4 6 8]]

AB has a shape (4, 3)

C describes the number of units of flour that is needed for a loaf of bread


***
# Mathematics with arrays


## Task 1
Create ``Numpy Arrays`` for all the following matrices. Use **like-named** `variables` for the different matrices.



**EXAMPLE:**

```python
M = np.array(...)
```

![task_1](imgs/matritzen_1.png)



**Questions:**
- What shape does `R` have?

In [162]:
import math
M = np.array([[1,7],[4,2]])
N = np.array([[6,0],[0,5]])
P = np.array([[-math.pi,-math.pi],[-math.pi,-math.pi]])
Q = np.array([[math.e + math.sqrt(2), math.e],[math.e, math.e + math.sqrt(2)]])
R = np.array([[M,N],[P,Q]])
S = np.array([[M+N,np.zeros((2,2))],[np.zeros((2,2)), P/math.pi]])

print(R.shape)

(2, 2, 2, 2)


## Task 2

Also calculate:

![augabe2](imgs/matritzen_2.png)

Use only **standard operators**

In [13]:
res1 = R+S
res2 = R.transpose()
res3 = M@N
res4 = N@M

***
# Manual Mathematics

Do the following calculations **by hand**:

**Given** are the following matrices:

![manual_1](imgs/manual_task_1.png)

Which of the following **calculations** are **possible**? Calculate them.
Please note that you have to perform **matrix multiplication**.

![manual_1_1](imgs/manual_task_1_1.png)






- AA can be calculated since the matrix is square:  
[1, -6, -4]  
[-2, 4, 4]  
[-3, 6, 4]

- AB don't have the same internal factor (3x3 | 2x3);
- AC don't have the same internal factor (3x3 | 1x3);
- AD can be calculated since they have the same internal factor (3x3 | 3x1):  
[-7]  
[4]  
[3]    
- BA can be calculated since they have the same internal factor (2x3 | 3x3):  
[7, 1, -11]  
[0, -8, -4]
- BB don't have the same internal factor (2x3 | 2x3);
- BD can be calculated since they have the same internal factor (2x3 | 3x1):  
[-2]  
[-10]  
- CA can be calculated since they have the same internal factor (1x3 | 3x3):  
[5, 0, -6]  
- CD can be calculated since they have the same internal factor (1x3 | 3x1):  
[1]  
- DC can be calculated since they have the same internal factor (3x1 | 1x3):  
[-2, 3, -1]  
[0, 0, 0]  
[6, -9, 3]

***
end