# Assignment work SW08 - PYTHON BASICS  

These are the self-study tasks for the semester week, which you will solve within a week in your JupyterHub environment. After completing your work, download a copy of the Jupyter notebook file locally to your laptop (right-click on the file in the JupyterHub file browser -> Download).

On ILIAS you will find the corresponding scheduled work assignments every week, where you will upload your solved Jupyter notebook file. After you have submitted your work, you will receive a corresponding sample solution for the work assignment. Your submission will not be corrected. Although the work assignments are marked "mandatory", there are no tests in the module. The grades from the tests during the semester count.

We wish you much success!

# Math Tasks  


## Task 1 - deg2rad

- Define the **function** ``deg2rad(angle)`` which can convert the angle from **degrees** to **radians**. Use only standard operators (``+,-,...``)

- Test this

# Task 2 - rad2deg

- Define the inverse function `rad2deg(radians)`. Use only standard operators (``+,-,...``)
- Test this

# Task 3 - Ball Surface

- Define the function ``ball_surface(radius)``, which can calculate and **return** the **surface area of ​​a sphere**.
- Give the function a **default value** of `` 5``
- Test this

# Array tasks

## Array Creation I

Write a NumPy program to create a **3x3 matrix with values ​​between 2 and 10**. Assign the array to the variable ``arr_3d``.

**Tip:**
- ``np.arrange()``
- ``np.reshape()``

**Result:**

```
array([[ 2, 3, 4],
[ 5, 6, 7],
[ 8, 9, 10]])
```

# Invert

- Convert `arr_3d` to a **1D array**.
- Assign the result to the variable `arr_1d`.

**Result:**
```
array([ 2, 3, 4, 5, 6, 7, 8, 9, 10])
```

- **Invert** the order of the array (the first element becomes the last).


**Result**:
```
array([10, 9, 8, 7, 6, 5, 4, 3, 2])
```

## Read information
Print the following information from the arrays `arr_3d` and `arr_1d`.

- Shape
- Number of elements
- Number of dimensions

## Read values:

Read the following values ​​from `arr_1d` **in one statement** (via slicing):

- `[2,4,6]`
- `[10,9,8,7]`

Read the following values ​​from `arr_3d` **in a statement** (via slicing):

- `[2,3,4]`
- `[2,5,8]`
- `[[6,7],[9,10]]`


## Array Arithmetic I

Create the following array & output it

![Alt ​​text](imgs/array_zeros.png)

## Array manipulation

1. **Transpose** the given array and store it in a new variable.
- Print the **shape** of both arrays.

2. Perform a **matrix multiplication** of the given and the transposed array.
- Store the result as a new variable (`z`).
- Print the **form** of `z`
- Return the **number of dimensions** of `z`

3. **Reform`z`** into the form ``(10,10,1)``.
- Print the form of `z`
- Print the number of dimensions of `z`

4. **Type conversion:**
- Print the type of array `z`
- convert the array type to a `float`
- convert the type of the array to a `bool`
- what happens?

# Text comprehension + Python

In a bakery, **three** different types of **dough** $T_1, T_2, T_3$ are made from **four** different
**Types of flour** $M_1, M_2, M_3, M_4$ are produced. From the dough types **three** different
Types of **bread** $B_1, B_2, B_3$ baked.

The following **tables** show:

1. How many units of **each type of flour** are needed **per unit of dough** of the different **dough types**
2. How many units of **each type of dough** are needed per **loaf of bread**:

![text_1](imgs/text_1_eng.png)


Let $A$ be the $(4 × 3)$ matrix from the **first table (left)** and $B$ be the $(3 × 3)$ matrix
from the **second table**.

## Task

- Create the two Maritzen $A$ and $B$

- Calculate $C$ which is the matrix describing the number of units of **flour**
that is needed for a loaf of **bread** of type $B$ : Express the matrix $C$
by $A$ and $B$. **Give reasons for your answer**

- What shape does $C$ have?

- What does an arbitrary entry in $C_{ij}$ describe


# Mathematics with arrays


## Task 1
Create ``Numpy Arrays`` for all the following matrices. Use **like-named** `variables` for the different matrices.



**EXAMPLE:**

```python
M = np.array(...)
```

![task_1](imgs/matritzen_1.png)



**Questions:**
- What shape does `R` have?

## Task 2

Also calculate:

![augabe2](imgs/matritzen_2.png)

Use only **standard operators**

# Manual Mathematics

Do the following calculations **by hand**:

**Given** are the following matrices:

![manual_1](imgs/manual_task_1.png)

Which of the following **calculations** are **possible**? Calculate them.
Please note that you have to perform **matrix multiplication**.

![manual_1_1](imgs/manual_task_1_1.png)




